### ISSUE TITLE
Staking Pallet changes

### ISSUE THREAD

**Issue by theclimacoin** [climatechglobal/climacoin-node#11]
### Tasks

- [x] Change Reward source to Reward trait 
- [x] Reward Remainder should be removed
- [x] The minimum staking Amount is 1M CLC for validators and 1K CLC for nominators.
- [x] Configure offence pallet to slash validator 
- [x] Validator and Nominator payout should be configured
