### ISSUE TITLE
Token Minting

### ISSUE THREAD

**Issue by theclimacoin** [climatechglobal/climacoin-node#14]
### Description
Every day tokens will be minted according to the [tokenomics](https://docs.google.com/spreadsheets/d/1aY_FZA0eqWj2p8ua_oFx5rubs8EaSgu-/edit#gid=1446455257).

### Tasks

- [ ] Create a minting pallet
- [ ] At the end of each day, tokens should be minted according to the logic mentioned below.
- [ ] Minted tokens should be transferred to Treasury as a Negative Imbalance.
  ```
  Initial Suppy = 29,000,000,000
  Up to Block number 63,07,200  [End of 1 Year] (1 % of Initial Supply)/365 should be minted every day
  After that, up to Block number 3,15,36,000 [End of 5 years] (2 % of Initial Supply)/365 should be minted every day
  After that, up to Block number 6,30,72,000 [End of 10 years] (3 % of Initial Supply)/365 should be minted every day
  Then after that minting should stop.
  ```
